---
- name: Test ansible
  hosts: nsx
  vars_files:
  - nsxt_policy_segment_vars.yaml
  tasks:
    - name: Display hostname
      debug:
        msg: "the hostname is {{nsx_hostname}}"
    - name: Display segment
      debug:
        msg: "the segment is: {{segment_name}}"